/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GammaRedeemer } from "./GammaRedeemer";

export { GammaRedeemer__factory } from "./factories/GammaRedeemer__factory";
